apiVersion: apps/v1
kind: Deployment
metadata:
  name: callList
  labels:
    app: callList
spec:
  replicas: 1
  selector:
    matchLabels:
      app: callList
  template:
    metadata:
      labels:
        app: callList
    spec:
      containers:
        - name: callList
          image: username/callList:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5